version: "3"
services:

  # FAIR Data Point client	
  fdp_client:
    image: fairdata/fairdatapoint-client:1.16.3
    hostname: fdpclient
    restart: always
    environment:
      FDP_HOST: fdp
    volumes:
      - ./fdp/variables.scss:/src/scss/custom/_variables.scss:ro
      - ./fdp/assets:/usr/share/nginx/html/assets:ro
      - ./fdp/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    depends_on:
      - fdp
    ports:
      - 7070:80  # You should/must close this port, if you are using hitch
    networks:
      - flair-default


  graphdb:
    image: ontotext/graphdb:10.1.2
    restart: always
    hostname: graphdb
    ports:
      - 127.0.0.1:7200:7200
    volumes:
      - flair-graphdb:/opt/graphdb/home
    networks:
      - flair-default

  fdp:
    image: fairdata/fairdatapoint:1.16.2
    restart: always
    hostname: fdp
    volumes:
      - ./fdp/application-flair.yml:/fdp/application.yml:ro
    depends_on:
      - mongo
      - graphdb
    networks:
      - flair-default
        
  updater:
    image: markw/fdp-metadata-updater:0.0.2
    restart: always
    hostname: updater
    environment:
      DATA_SPARQL_ENDPOINT: ${DATA_SPARQL_ENDPOINT}
      DIST_RECORDID: ${DIST_RECORDID}
      DATASET_RECORDID: ${DATASET_RECORDID}
      DOMAIN: ${DOMAIN}
      FDP_USERNAME: ${FDP_USERNAME}
      FDP_PASSWORD: ${FDP_PASSWORD}
    networks:
      - flair-default
      
  # Mongo for FDP server    
  mongo:
    image: mongo:4.2.3
    hostname: mongo
    restart: always
    volumes:
      - flair-mongo-data:/data/db
      - flair-mongo-init:/docker-entrypoint-initdb.d/
    networks:
      - flair-default

  cde-box-daemon: 
    image: markw/cde-box-daemon:0.5.2    # to use the CARE-SM models with teh care-sm-toolkit
    container_name: cde-box-daemon
    environment:
      GraphDB_User: ${GraphDB_User}
      GraphDB_Pass: ${GraphDB_Pass}
      baseURI: ${baseURI}
    depends_on:
      - caresm
      - yarrrml-rdfizer
    ports:
      - 127.0.0.1:4567:4567
    volumes:
      - ./data:/data
      - ./config:/config
    networks:
      - flair-default
                
  yarrrml-rdfizer:
    image: markw/yarrrml-rml-ejp:0.0.3
    container_name: yarrrml-rdfizer
    hostname: yarrrml-rdfizer
    environment:
      # (nquads (default), trig, trix, jsonld, hdt, turtle)
      - SERIALIZATION=nquads
#    ports:
#      - "4567:4567"
    volumes:
      - ./data:/mnt/data
    networks:
      - flair-default



volumes:
  flair-graphdb:
    external: true
  flair-mongo-data:
    external: true
  flair-mongo-init:
    external: true
  flair-fdp-server:
    external: true

networks:
  flair-default:
