version: "2.0"
services:

  solid: 
    image: solidproject/community-server
    environment:
#       CSS_CONFIG: /community-server/config/default.json
       CSS_CONFIG: /community-server/config/file.json
       CSS_LOGGING_LEVEL: debug
       # CSS_ROOT_FILE_PATH=/data

    volumes:
       - $PWD/data:/data
    ports:
      - "3000:3000"
