version: "3.0"
services:

  flair-gg-vp-server:
#    image: markw/flair-gg-vp-server:0.0.9
    image: markw/flair-gg-vp-server:0.0.10
    container_name: "flair-gg-vp-server"
    hostname: "flairgg"
    ports:
      - "4567:4567"
    command: ruby /server/vp-interface/app/controllers/application_controller.rb -o 0.0.0.0
    volumes:
      - ./cache:/server/vp-interface/cache/
    environment:
      - RUBYOPT=-W0 -KU -E utf-8:utf-8
      - FDPINDEX="https://index.bgv.cbgp.upm.es/"
    depends_on:
      - swagger

  swagger:
    image: swaggerapi/swagger-ui
    container_name: "swagger"
    ports:
      - "4566:8080"
    environment:
      - SWAGGER_JSON_URL=https://vp.bgv.cbgp.upm.es/flair-gg-vp-server
