version: "3.0"
services:

  flair-gg-vp-server:
    image: markw/flair-gg-vp-server:0.0.8
    restart: always
    container_name: "flair-gg-vp-server-bgv"
    hostname: "flairgg"
    ports:
      - "4567:4567"
    command: ruby /server/vp-interface/app/controllers/application_controller.rb -o 0.0.0.0
    volumes:
      - ./cache:/server/vp-interface/cache/
    environment:
      - RUBYOPT=-W0 -KU
      - FDPINDEX=https://index.bgv.cbgp.upm.es/
#      - RUBYOPT=-W0 -KU -E utf-8:utf-8
    depends_on:
      - swagger

  swagger:
    image: swaggerapi/swagger-ui:latest
    restart: always
    container_name: "swagger"
    ports:
      - "4566:8080"
    environment:
      - SUPPORTED_SUBMIT_METHODS=${SUPPORTED_SUBMIT_METHODS}
      - URLS=${URLS}
      - BASE_URL='/swagger'   # for our reverse proxy

  ldp:
    image: markw/ldp_server:latest
    hostname: flair-ldp
    ports:
      - 1111:1111
      - 8890:8890
